### PR TITLE
Update the build instructions

### PR DESCRIPTION
**Pull request by hsorby**
There have been some problems building on Windows with Visual Studio.  These changes are looking to fix those issues.

We are also adding some continuous integration testing that will (should) help with future pull requests. (This should of course have been done in a separate PR, apologies for doing it this way.)

### CODE REVIEW

**Comment by hsorby** [comment]
I have tested this on Windows with Intel oneAPI Fortran, Ubuntu 20.04 with and without SuperLU, and macOS Big Sur.

**Comment by acreegan** [comment]
This is major progress but still not quite working for me. The build now succeeds with no errors on Visual Studio for me. I am able to install the python package, but I have not yet been able to actually import the libraries yet. Here is my terminal output:

````
(venv) C:\Users\acre018\github\hugh_lungsim\lungsim_build>python
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from aether.diagnostics import set_diagnostics_on
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\acre018\github\hugh_lungsim\lungsim_build\venv\lib\site-packages\lungnoodle.aether-0.1.0-py3.9-win-amd64.egg\aether\diagnostics.py", line 13, in <module>
ImportError: cannot import name '_diagnostics' from 'aether' (C:\Users\acre018\github\hugh_lungsim\lungsim_build\venv\lib\site-packages\lungnoodle.aether-0.1.0-py3.9-win-amd64.egg\aether\__init__.py)
>>>
````

**Comment by hsorby** [comment]
The one thing that I think is stopping you from having a working Aether library is the `dll` loading.  In Python 3.8+ the path for loading dlls has been, in my opinion, nerfed.

You will need to have the Fortran libraries that the Aether library needs on your system path, or Python dll load path.  To check if this is your problem you can try adding the following before you attempt to import Aether.  I will also mention that this is a Windows specific problem and doesn't apply to other oses.

```
import os
os.add_dll_directory(r"C:\Program Files (x86)\Intel\oneAPI\compiler\2022.0.2\windows\redist\intel64_win\compiler")
```

I'm just educated guessing on the path here, you redistributable directory might be located in a different place given factors like the version of the Intel Fortran compiler.  Hopefully the path provides enough of a hint for you to get the correct path for your system.

**Comment by acreegan** [comment]
Hmm, interesting. Your suggestion only works for me when I run python from within the src\bindings\python\Debug folder. Here is what I did:

From the lungsim_build folder, try to import set_diagnostics_on:
```
(venv) C:\Users\acre018\github\hugh_lungsim\lungsim_build>python
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from aether.diagnostics import set_diagnostics_on
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\acre018\github\hugh_lungsim\lungsim_build\venv\lib\site-packages\lungnoodle.aether-0.1.0-py3.9-win-amd64.egg\aether\diagnostics.py", line 13, in <module>
ImportError: cannot import name '_diagnostics' from 'aether' (C:\Users\acre018\github\hugh_lungsim\lungsim_build\venv\lib\site-packages\lungnoodle.aether-0.1.0-py3.9-win-amd64.egg\aether\__init__.py)
```
We get cannot import name. Try adding dll directory:
```
>>> import os
>>> os.add_dll_directory(r"C:\Program Files (x86)\Intel\oneAPI\compiler\2022.0.0\windows\redist\intel64_win\compiler")
<AddedDllDirectory('C:\\Program Files (x86)\\Intel\\oneAPI\\compiler\\2022.0.0\\windows\\redist\\intel64_win\\compiler')>
>>> from aether.diagnostics import set_diagnostics_on
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\acre018\github\hugh_lungsim\lungsim_build\venv\lib\site-packages\lungnoodle.aether-0.1.0-py3.9-win-amd64.egg\aether\diagnostics.py", line 13, in <module>
ImportError: cannot import name '_diagnostics' from 'aether' (C:\Users\acre018\github\hugh_lungsim\lungsim_build\venv\lib\site-packages\lungnoodle.aether-0.1.0-py3.9-win-amd64.egg\aether\__init__.py)
>>> ^Z
```
Same error.

Move to src\bindings\python\Debug and try to import set_diagnostics_on:
```
(venv) C:\Users\acre018\github\hugh_lungsim\lungsim_build>cd src\bindings\python\Debug

(venv) C:\Users\acre018\github\hugh_lungsim\lungsim_build\src\bindings\python\Debug>python
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from aether.diagnostics import set_diagnostics_on
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\acre018\github\hugh_lungsim\lungsim_build\src\bindings\python\Debug\aether\diagnostics.py", line 13, in <module>
    from . import _diagnostics
ImportError: DLL load failed while importing _diagnostics: The specified module could not be found.
```
Now the error mentions failure to load DLL.

Try adding dll directory:
```
>>> import os
>>> os.add_dll_directory(r"C:\Program Files (x86)\Intel\oneAPI\compiler\2022.0.0\windows\redist\intel64_win\compiler")
<AddedDllDirectory('C:\\Program Files (x86)\\Intel\\oneAPI\\compiler\\2022.0.0\\windows\\redist\\intel64_win\\compiler')>
>>> from aether.diagnostics import set_diagnostics_on
>>> ^Z
````
And we import without errors

One other point about the Intel dll, I didn't realize this package would still require a dll from the Fortran compiler. This would obviously need to be included if the package was built on a CI system and installed with pip. How would we go about doing that?

**Comment by hsorby** [comment]
For the first scenario, my first guess would be that you do not have the Aether python package setup as you think you do.

I'm pleased that the problem, as such, is solved.

Users of the Aether package would have to install the redistributable binaries for the Intel compiler themselves.  You can include the Intel dlls in the package itself but I am not a lawyer is all I am going to say on that idea.  I don't have a link to the redistributable installers but they must be available somewhere.

**Comment by acreegan** [comment]
It could certainly be that my python package is not set up properly! I just used python setup.py install with my venv activated. If this is working for you would you be able to write a more detailed list of commands you use to build/install/test?

I hadn't thought about the legality of including the dlls, but I kind of thought that was the point of the term redistributable. I also thought this might have been an issue you had already solved with opencmiss.zinc but I see now that that is C++ based.

**Comment by hsorby** [comment]
If you try building this with Python bindings now and install them with 

```
pip install -e <some-path>\src\bindings\python\Release
```

Things should work.

**Comment by haribalankumar** [comment]
Changes above are for windows. Still I have checked on Linux 20.04 and it builds fine. Can you merge this PR please.

**Pull request merged**
