### PR TITLE
Elastic alpha fix

### PR DESCRIPTION
**Pull request by behdadebsh**
ealstic_alpha vessel model has inverse elasticity values compared to elastic_g0_beta. The implementation of when Ptm > Ptmmax is corrected.

### CODE REVIEW

**Comment by alysclark** [comment]
@behdadebsh mostly looks good - but - not sure what the .nfs* files you have committed are - files of this type need to be added to .gitignore and pull request updated.

**Comment by behdadebsh** [comment]
> @behdadebsh mostly looks good - but - not sure what the .nfs* files you have committed are - files of this type need to be added to .gitignore and pull request updated.

removed the temp files. Those are hidden files created by ATOM text editor while editing the code. I have updated the pull request.

**Comment by hsorby** [comment]
You should consider adding the `.nfs*` to the `.gitignore` file so that it doesn't happen again.

I like how you are working in a feature branch, nice!

**Comment by behdadebsh** [comment]
> You should consider adding the `.nfs*` to the `.gitignore` file so that it doesn't happen again.
> 
> I like how you are working in a feature branch, nice!

Thanks! I added .nfs to gitignore. Pull request updated

**Pull request merged**
