### PR TITLE
2dfrom1d

### PR DESCRIPTION
**Pull request by tawhai**
New subroutines for creating a 2d surface mesh (templated) over a 1d tree. The surface mesh can be exported or written out as a Gmsh .geo file.

### CODE REVIEW

**Comment by behdadebsh** [comment]
What is the file bob.f90 for? It shows it as empty if I'm not mistaken?

**Comment by behdadebsh** [comment]
The subroutine write_elem_geometry_2d in geometry.f90, does this export the 2d surface elem file? If so, shouldn't it be in exports.f90? And as far as I remember the export_2d_geometry has and issue before.

**Comment by tawhai** [comment]
My mistake – I’ve removed that module (contained rubbish).


Professor Merryn Tawhai, FRSNZ
Director The Medical Technologies CoRE
Deputy Director Auckland Bioengineering Institute
Level 7, Auckland Bioengineering House
70 Symonds Street, AUCKLAND 1010
Phone +64(9) 923 5119

**Comment by tawhai** [comment]
This subroutine writes out the cmiss .ipelem format file (not the cmgui .exelem file). So this is the correct place.


Professor Merryn Tawhai, FRSNZ
Director The Medical Technologies CoRE
Deputy Director Auckland Bioengineering Institute
Level 7, Auckland Bioengineering House
70 Symonds Street, AUCKLAND 1010
Phone +64(9) 923 5119

**Comment by alysclark** [comment]
@tawhai this pull request contains conflicts to the main branch - i am not sure why as i believe the last pull request i accepted was from you. However, you will be better placed to make the calls about which parts should be retained than me - so if you look at the pull request you should see the option to resolve conflicts, can you follow that and delete the incorrect options?

**Comment by tawhai** [comment]
Conflicts merged.


Professor Merryn Tawhai, FRSNZ
Director The Medical Technologies CoRE
Deputy Director Auckland Bioengineering Institute
Level 7, Auckland Bioengineering House
70 Symonds Street, AUCKLAND 1010
Phone +64(9) 923 5119

**Comment by alysclark** [comment]
@tawhai - OK one last issue to resolve between us. I see you have added something that groups elements into a type "no_type" set up as part of elem_ordrs, although i admit i haven't looked too deep into what you do with this. In the perfusion model i have something similar (I think) defined by ne_group which defines a 'type' of element in elem_fields. Better to have just one way to do this? If so, do you have an opinion on which way?

**Comment by tawhai** [comment]
I use elem_ordrs because this is an integer array that relates to the tree connectivity (elem_fields should be for continuous variables?) . For conducting airways I set no_type =1 and respiratory=0. I chose these for convenience because it means that when I am calculating the volume of a branching mesh I can exclude the branching respiratory airways from the calculation (without a conditional statement), because their volume is already accounted for in the elastic unit volume.

Before we decide on this, we have a bigger question: should we adopt independent arrays for the vascular and airway trees? So far this has not been an issue, but going forward if we want to iteratively solve for V and Q it would be more convenient to have separate arrays instead of having to identify the specific block of elements that relate to airways or vessels.

**Comment by alysclark** [comment]
OK - i will merge this request and raise two issues 1) using no_type rather than ne_group for perfusion modelling, and 2) separation of airway and vascular trees (whilst retaining enough generalisation such that subroutines like resistance calculation can be reused - avoiding replication of code).

**Pull request merged**
